# Generated by Django 4.0.4 on 2022-04-20 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('price', models.FloatField()),
                ('bedrooms', models.FloatField()),
                ('bathrooms', models.FloatField()),
                ('sqft_living', models.FloatField()),
                ('sqft_lot', models.FloatField()),
                ('floors', models.FloatField()),
                ('waterfront', models.IntegerField()),
                ('view', models.IntegerField()),
                ('condition', models.IntegerField()),
                ('sqft_above', models.FloatField()),
                ('sqft_basement', models.FloatField()),
                ('yr_built', models.TextField()),
                ('yr_renovated', models.TextField()),
                ('street', models.TextField()),
                ('city', models.TextField()),
                ('statezip', models.TextField()),
                ('country', models.TextField()),
            ],
        ),
    ]
